on:
  push:
    branches:
      - 'production'
      - 'demo'
      - 'main'
      - '[0-9]+**'
      - '[a-zA-Z]+/[0-9]+**'
      - '!old/**'
      - '!nobuild/**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      DEPLOY:
        type: boolean
        description: Deploy artifacts
        default: false
        required: false

jobs:
  up:
    runs-on: ubuntu-22.04
    #runs-on: macos-13
    concurrency:
      group: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production' || inputs.DEPLOY) && 'concurrency-counter-increment' || github.run_id }}
      #cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/production' && inputs.DEPLOY == false }}
      cancel-in-progress: false
    steps:
      - name: Echo
        run: |
          echo $RUNNER_TEMP
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.run_number: ${{ github.run_number }}"
          echo "github.run_attempt: ${{ github.run_attempt }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.ref: ${{ github.ref }}"
          echo "build job url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Is fork: ${{ github.event.pull_request.head.repo.fork == true }}"
          echo "Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Ref: ${{ github.head_ref || github.ref_name }}"
          echo "Deploy: ${{ inputs.DEPLOY }}"
          echo "Is deploy: ${{ inputs.DEPLOY && 'yes' || 'no' }}"
          echo "Is main: ${{ github.ref == 'refs/heads/main' && 'yes' || 'no' }}"
          echo "Is production: ${{ github.ref == 'refs/heads/production' && 'yes' || 'no' }}"
          echo "Concurrency group: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production' || inputs.DEPLOY) && 'concurrency-counter-increment' || github.run_id }}"
          echo "Cancel in progress: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production' || inputs.DEPLOY) && 'false' || 'true' }}"

      - name: env
        run: export | grep -vi "token"

      - name: Check if triggered manually
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "This workflow was triggered manually."
          else
            echo "This workflow was triggered automatically."
          fi

      - name: Trigger only on dispatch.
        if: github.event_name == 'workflow_dispatch'
        run: echo "This workflow was triggered automatically."

      - name: Print event object
        run: echo '${{ toJson(github.event) }}' | jq .

      - name: Print event.pull_request object
        run: echo '${{ toJson(github.event.pull_request) }}' | jq .

      - name: Print pull_request info
        run: |
          echo 'PR number: ${{ github.event.pull_request.number }}'
          echo 'PR source: ${{ github.event.pull_request.head.ref }}'
          echo 'PR target: ${{ github.event.pull_request.base.ref }}'

      - name: Counter
        id: incremented
        run: |
          NUM=$(("${{ vars.NUM }}" + 1))
          echo "Var sum: $NUM"
          echo "number=$NUM" >> "$GITHUB_OUTPUT"

      - name: Conditionally skip
        id: conditional
        if: ${{ inputs.DEPLOY == true }}
        run: |
          echo "Conditionally deploy.."

      - name: Print step outputs
        run: |
          echo "${{ toJSON(steps.conditional.outputs) }}"

      - name: Only when skipped.
        if: ${{ steps.conditional.outputs.step_skipped == 'true' }}
        run: |
          # Your step 2 commands here

      - name: Update vars.NUM
        if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production' || inputs.DEPLOY == true)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.rest.actions.updateRepoVariable({ 
              "owner": "${{ github.repository_owner }}", 
              "repo": "${{ github.event.repository.name }}",
              "name": "NUM", 
              "value": "${{ steps.incremented.outputs.number }}" 
            });
            
      - name: Sleep
        run: |
          sleep 30
