on:
  pull_request:
  workflow_dispatch:
    inputs:
      DEPLOY:
        type: boolean
        description: Deploy artifacts
        default: false
        required: false

jobs:
  up:
    runs-on: ubuntu-22.04
    #runs-on: macos-13
    concurrency:
      group: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production' || vars.DEPLOY == true) && 'concurrency-counter-increment' || github.ref }}
      cancel-in-progress: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production' || vars.DEPLOY == true) && false || true }}
    steps:
      - name: Echo
        run: |
          echo $RUNNER_TEMP
          echo "github.repository: ${{ github.repository }}"
          echo "Is fork: ${{ github.event.pull_request.head.repo.fork == true }}"
          echo "Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Ref: ${{ github.head_ref || github.ref_name }}"

      - name: Counter
        id: incremented
        run: |
          NUM=$(("${{ vars.NUM }}" + 1))
          echo "Var sum: $NUM"
          echo "number=$NUM" >> "$GITHUB_OUTPUT"

      - name: Update vars.NUM
        if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production' || inputs.DEPLOY == true)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.rest.actions.updateRepoVariable({ 
              "owner": "${{ github.repository_owner }}", 
              "repo": "${{ github.event.repository.name }}",
              "name": "NUM", 
              "value": "${{ steps.incremented.outputs.number }}" 
            });
            
      - name: Sleep
        run: |
          sleep 30
