on:
  pull_request:
  workflow_dispatch:
    inputs:
      DEPLOY:
        type: boolean
        description: Deploy artifacts
        default: false
        required: false

jobs:
  up:
    runs-on: ubuntu-22.04
    #runs-on: macos-13
    concurrency:
      group: ${{ vars.DEPLOY == true && 'concurrency-counter-increment' || github.ref }}
      cancel-in-progress: ${{ vars.DEPLOY == true && false || true }}
    steps:
      - name: Echo
        run: |
          echo $RUNNER_TEMP
          echo "github.repository: ${{ github.repository }}"
          echo "Is fork: ${{ github.event.pull_request.head.repo.fork == true }}"
          echo "Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Ref: ${{ github.head_ref || github.ref_name }}"
      - name: Counter
        run: |
          echo "Var sum: $(("${{ vars.NUM }}" + 1))"
      - name: Sleep
        run: |
          sleep 60
