on:
  pull_request:
  workflow_dispatch:

jobs:
  up:
    runs-on: ubuntu-22.04
    #runs-on: macos-13
    steps:
      - name: Echo
        run: |
          echo $RUNNER_TEMP
          echo "github.repository: ${{ github.repository }}"
          echo "Is fork: ${{ github.event.pull_request.head.repo.fork == true }}"
          echo "Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Ref: ${{ github.head_ref || github.ref_name }}"
          echo "Var: ${{ vars.NUM + 1 }}"
