name: Reusable

on:
  workflow_call:
    inputs:
      languages:
        required: false
        default: '["java", "javascript"]'
        type: string

jobs:
  analyze:
    name: matrix-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(inputs.languages) }}

    steps:
    - name: Echo
      run: |
        echo "Language: ${{ matrix.language }}"
