name: Safe secrets dump

on:
  workflow_dispatch:

jobs:
  export-and-encrypt-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Secrets
        id: fetch-secrets
        run: echo "${{ toJson(secrets) }}" > secrets.json
      
      - name: Encrypt Secrets
        run: |
          # Encrypt the JSON file containing secrets
          openssl aes-256-cbc -pass pass:${{ secrets.ENCRYPTION_KEY }} -md sha256 -in secrets.json -out encrypted_secrets.json
      
      - name: Upload Encrypted Secrets
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets
          path: encrypted_secrets.json
